language: java
sudo: true

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq csvtool

install:
- wget -O robocode-setup.jar "http://downloads.sourceforge.net/project/robocode/robocode/1.9.2.5/robocode-1.9.2.5-setup.jar?r=&ts=1452208388&use_mirror=iweb"
- unzip robocode-setup.jar

script:
- java -Xmx512M -Dsun.io.useCanonCaches=false -cp libs/robocode.jar robocode.Robocode
  -battle battles/darby.battle -nodisplay -results results.txt

after_script:
- csvtool readable results.txt -t TAB

notifications:
  slack:
    secure: bjoRu5fcOFbBppAnfC+po6B5yIP7xi6u/bdP9l0Da6sh0Vxf79eHKHiYnaDipO5GmH29xGvoq2p4+PpPjXrHSH/i6QjXBShPYelrdu320wD7d5Tope5kehzA+mCUsTSM5snuAmVoDnZh4pM9kxqRvqQaRr+XaIKFpDkCRHvx+I6oPR7LLobJkA6EDH1cJxnbp375dY7vrx8X9ujgPjLOfqh/mJAUC6u1mnBmETaCbvfBBhyzThZCoWLhKLNn1/osOi96CVauATPoCqmMCvSuZm++aKhnZU2v6Op0/4BsaYkLL8XEQRxJSjTySOiQQZh4pH1je65Ojux18fxqQtoOMkNFLo/E6TwjKrcrNKMQN7iGgXpxHTI7OmyhlESMthnZTyCrdm0E7A5wG7BU9Vph8HlNUfFhlOiTJoRtnS3JD1bN4RJoGhdYiEnL9fH8rypBHNxyBsLTT9GD+njb/ryVpobHR1UwrgugclTYfK/hq44HmnvqAXDio4XysctU1VxbptVxzKcdA01tyUnlgBoGxQ24EtADIIM9fa0GDMknYMyNcph8DUg2pyE11obTl1VYslfsQa/Er983p5tvc42/RFoUAQgQjVNj7JrNWxhVSSnwIUO0fkPwbseASUoPWO3sYNouMLnSigyZ0+OVg4Bw0NrTuFw9pxo9CeMduHC8qtk=
