language: java
sudo: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq csvtool
install:
  - wget -O robocode-setup.jar "http://downloads.sourceforge.net/project/robocode/robocode/1.9.2.5/robocode-1.9.2.5-setup.jar?r=&ts=1452208388&use_mirror=iweb"
  - unzip robocode-setup.jar

script:
  - java -Xmx512M -Dsun.io.useCanonCaches=false -cp libs/robocode.jar robocode.Robocode -battle battles/darby.battle -nodisplay -results results.txt

after_script:
  - csvtool readable results.txt -t TAB
